<div class="pp-buttons-container">
    <p>
        <button data-action="subscriber_data" class="send_mass_data" id="sub_mass_data" type="button">
            <?= $block->escapeHtml(__('Start Syncing')) ?>
        </button>
    </p>
</div>

<?php if ($block->dataSynced()): ?>
    <script type="text/javascript">
        document.getElementById("sub_mass_data").setAttribute("disabled", "true");
    </script>
<?php else: ?>
    <style>
        #row_waymoreroutee_exportdata_mass_import_nl .note span{
            display: none;
        }
    </style>
<?php endif; ?>
