<?php
/**
 * @var Routee\WaymoreROutee\Block\System\Config\SendProductMassData $block
 */

echo $block->getButtonHtml();
?>

<script>
    const url = "<?= $block->getAjaxUrl(); ?>";
    requirejs(['jquery'], function($) {
        let dtransferred = "<?= $block->completeDataSynced(); ?>";
        let getuuid = "<?= $block->getUUID(); ?>";
        if (!getuuid) {
            $(".send_mass_data").attr("disabled", "true");
        }

        if (getuuid) {
            $('#waymoreroutee_general_username').attr('readonly', 'readonly');
            $('#waymoreroutee_general_password').attr('readonly', 'readonly');
        }

        if (dtransferred) {
            let msg = '<div class="message message-success success"><div data-ui-id="messages-message-success">You have been synchronized with waymore.routee.net.</div></div>';
            $('#waymoreroutee_general-head').before(msg);
        }
    });
</script>


<?php if (!$block->productSynced()) { ?>
        <style>
            #row_waymoreroutee_exportdata_mass_import_product .note span{
                display: none;
            }
        </style>
<?php } ?>
