<div class="pp-buttons-container">
    <p>
        <button data-action="product_data" class="send_mass_data" id="product_mass_data" type="button">
            <?= $block->escapeHtml(__('Start Syncing')) ?>
        </button>
    </p>
</div>

<script>
    const url = "<?= $block->getAjaxUrl(); ?>";
    requirejs(['jquery'], function($) {
        let dtransferred = "<?= $block->escapeHtml($block->completeDataSynced()); ?>";
        let getuuid = "<?= $block->escapeHtml($block->getUUID()); ?>";
        if (!getuuid) {
            $(".send_mass_data").attr("disabled", "true");
        }

        if (getuuid) {
            $('#waymoreroutee_general_username').attr('readonly', 'readonly');
            $('#waymoreroutee_general_password').attr('readonly', 'readonly');
        }

        if (dtransferred) {
            let msg = '<div class="message message-success success"><div data-ui-id="messages-message-success">You have been synchronized with waymore.routee.net.</div></div>';
            $('#waymoreroutee_general-head').before(msg);
        }
    });
</script>


<?php if ($block->productSynced()): ?>
        <script>
                document.getElementById("product_mass_data").setAttribute("disabled", "true");
        </script>
<?php else: ?>
        <style>
            #row_waymoreroutee_exportdata_mass_import_product .note span{
                display: none;
            }
        </style>
<?php endif; ?>
